stages:
  train:
    cmd: PYTHONPATH=src python src/rlll/train.py models
    deps:
      - src/rlll/train.py
    params:
    - train.max_epi
    - train.lr
    - train.mem_size
    - train.epsilon
    - train.epsilon_decay
    - train.gamma
    - train.batch_size
    - train.burn_in
    - train.dnn_update
    - train.dnn_sync
    - train.stack_size
    - train.hidden_size
    outs:
      - models:
          cache: false
      - eval/train/rewards.json:
          cache: false
      - eval/train/mean_rewards.json:
          cache: false
      - eval/train/steps.json:
          cache: false
    metrics:
      - eval/train/best_score.json:
          cache: false

plots:
  - Training-Rewards:
      x: episode
      y:
        eval/train/rewards.json: reward
        eval/train/mean_rewards.json: reward
  - Number-Steps:
      x: episode
      y:
        eval/train/steps.json: steps
