stages:
  train:
    cmd: PYTHONPATH=src python src/rlll/train.py models
    deps:
      - src/rlll/train.py
    params:
    - train.lr
    - train.mem_size
    - train.max_epi
    - train.epsilon
    - train.epsilon_decay
    - train.gamma
    - train.batch_size
    - train.burn_in
    - train.dnn_update
    - train.dnn_sync
    outs:
      - models
      - eval/train/rewards.json:
          cache: false
      - eval/train/mean_rewards.json:
          cache: false

plots:
  - Training-Rewards:
      x: step
      y:
        eval/train/rewards.json: reward
        eval/train/mean_rewards.json: reward