train:
  seed: 43
  max_epi: 2000
  lr: 0.0042
  mem_size: 10000
  burn_in: 1000
  epsilon: 0.5
  epsilon_decay: 0.957
  min_epsilon: 0.014
  gamma: 0.989
  batch_size: 8
  dnn_update: 4
  dnn_sync: 1000
  stack_size: 1
  hidden_size: 32
