train:
  seed: 43
  max_epi: 2000
  lr: 0.0032
  mem_size: 100000
  burn_in: 1000
  epsilon: 0.9
  epsilon_decay: 0.972
  min_epsilon: 0.012
  gamma: 0.988
  batch_size: 64
  dnn_update: 2
  dnn_sync: 2500
  stack_size: 2
  hidden_size: 32
