train:
  max_epi: 1000
  lr: 0.0017
  mem_size: 10000
  burn_in: 10000
  epsilon: 1.0
  epsilon_decay: 0.981
  gamma: 0.985
  batch_size: 16
  dnn_update: 1
  dnn_sync: 5000
  stack_size: 2
  hidden_size: 32
